name: GitHub Actions Demo
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
    
  pull_request:
    branches:
    - main
    
  schedule:
  - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      -run:
        echo: "The job was triggered by event ${{ github.event_name }}"
      -uses: actions/checkout@v3.0.2
      -name: list files in directory
      run: 
        echo: "repository ${{ github.repository }} contains: "  

        
      
