name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    - release/*
    
  pull_request:
    branches:
    - main
    
  schedule:
  - cron: "15 6 * * 0"

jobs:
  my_job:
    name: my tst job 
    runs-on: ubuntu-latest

